server:
  port: 10001
spring:
  datasource:
    url: jdbc:mysql://10.31.47.11:3306/cms?characterEncoding=UTF-8
    username: remote
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # 第一次简表create  后面用update
    show-sql: true
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: file:${file.path}
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://localhost:6060/eureka
#文件上传
file:
  path: D:/img/
  fileDomain: http://localhost:10001/