server:
  port: 9090
spring:
  cloud:
    gateway:
      routes:
        - id: v1
          uri: lb://finance-service
          order: 0
          predicates:
            - Path=/**
            - After=2019-11-09T10:11:00.129+08:00[Asia/Shanghai]
          #            - Header=token,[0-5]
          filters:
            - StripPrefix=0
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://localhost:6060/eureka