server:
  port: 9090
spring:
  cloud:
    gateway:
      routes:
        - id: jpa
          uri: lb://finance-service
          order: 0
          predicates:
            - Path=/api/service/**
            - After=2019-11-09T10:11:00.129+08:00[Asia/Shanghai]
          #            - Header=token,[0-5]
          filters:
            - StripPrefix=2
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:6060/eureka