server:
  port: 10002
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cms?characterEncoding=UTF-8
    username: remote
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: finance-service # 应用名称
  jpa:
    hibernate:
      ddl-auto: update  # 第一次简表create  后面用update
    show-sql: true
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:6060/eureka